version: '3.1'

services:
  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    command: yarn start:dev

  db:
    container_name: db
    image: postgres
    env_file:
      - .env.prod
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-postgres:/var/lib/postgresql/data

volumes:
  db-postgres:
