version: "3.1"

services:
  api:
    container_name: appointments-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    command: yarn start:dev

  db:
    container_name: appointments-db
    image: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-postgres:/var/lib/postgresql/data

volumes:
  db-postgres:
